services:
  - type: web
    name: idx-eod-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:http
    envVars:
      - key: HOST
        value: 0.0.0.0
