import type { ScanResult, SignalName } from './types';

export const MAX_SCREENER_HEADERS = [
  'Ticker',
  'Date',
  'LatestAvailableDate',
  'HistoryBars',
  'HistoryQuality',
  'Price',
  'ChangePct',
  'Signal',
  'ActiveSignals',
  'SignalGroup',
  'ActiveSignal',
  'SniperLocation',
  'LastActiveSignals',
  'LastActiveDate',
  'LastSniperLocation',
  'SignalAgeLabel',
  'AgeDays',
  'Trend',
  'TrendShort',
  'TrendMedium',
  'TrendLong',
  'Structure',
  'Regime',
  'RisenScore',
  'RisenInsideRolling',
  'RisenRecentUpBreak',
  'RisenVolSurge',
  'Quadrant',
  'AlphaStatus',
  'RVol',
  'VolPower',
  'VolRegime',
  'XRayBuyPowerPct',
  'XRaySellPowerPct',
  'RSI',
  'ADX',
  'PlusDI',
  'MinusDI',
  'EMA21',
  'EMA50',
  'EMA200',
  'Volume',
  'VolumeSMA20',
  'Score',
  'LogicNotes',
  'Strategy',
  'PortfolioCapital',
  'Buy1',
  'Buy2',
  'Buy3',
  'Buy4',
  'Weight1',
  'Weight2',
  'Weight3',
  'Weight4',
  'Lot1',
  'Lot2',
  'Lot3',
  'Lot4',
  'TotalLots',
  'TotalDeployed',
  'CashLeft',
  'AvgEntry',
  'TheoreticalAvgEntry',
  'StopLoss',
  'TP1',
  'TP2',
  'TP2Fib',
  'RiskBuy1Pct',
  'RiskAvgPct',
  'UpsideBuy1Pct',
  'UpsideAvgPct',
  'RewardRiskBuy1',
  'RewardRiskAvg',
] as const;

export function formatSignalList(signals: SignalName[]) {
  return signals.length ? signals.join(' + ') : '-';
}

export function formatSignalAge(result: ScanResult) {
  if (result.ageDays >= 999) return '-';
  return result.ageDays <= 1 ? 'NEW' : `${result.ageDays}d`;
}

export function getMaxScreenerExportDate(results: ScanResult[]) {
  return results.reduce(
    (current, item) => (item.latestDate > current ? item.latestDate : current),
    results[0]?.latestDate ?? new Date().toISOString().slice(0, 10),
  );
}

export function buildMaxScreenerRows(results: ScanResult[]) {
  return [
    MAX_SCREENER_HEADERS,
    ...results.map((item) => [
      item.ticker,
      item.latestDate,
      item.latestAvailableDate ?? '',
      item.historyBars,
      item.historyQuality,
      item.price,
      item.changePct,
      item.signal,
      formatSignalList(item.activeSignals),
      item.signalGroup,
      item.activeSignal ? 'TRUE' : 'FALSE',
      item.sniperLocation ?? '',
      formatSignalList(item.lastActiveSignals),
      item.lastActiveDate ?? '',
      item.lastSniperLocation ?? '',
      formatSignalAge(item),
      item.ageDays < 999 ? item.ageDays : '',
      item.status,
      item.trendShort,
      item.trendMedium,
      item.trendLong,
      item.structure,
      item.regime,
      item.risenScore,
      item.risenInsideRolling ? 'TRUE' : 'FALSE',
      item.risenRecentUpBreak ? 'TRUE' : 'FALSE',
      item.risenVolSurge ? 'TRUE' : 'FALSE',
      item.quadrant,
      item.alphaStatus,
      item.rvol,
      item.volPower,
      item.volRegime,
      item.xrayBuyPower,
      item.xraySellPower,
      item.rsi,
      item.adx,
      item.plusDi,
      item.minusDi,
      item.ema21 ?? '',
      item.ema50 ?? '',
      item.ema200 ?? '',
      item.records[item.records.length - 1]?.volume ?? '',
      item.volumeSma20 ?? '',
      item.score,
      item.reason.join(' | '),
      item.plan?.strategy ?? '',
      item.plan?.portfolioCapital ?? '',
      item.plan?.buy1 ?? '',
      item.plan?.buy2 ?? '',
      item.plan?.buy3 ?? '',
      item.plan?.buy4 ?? '',
      item.plan?.weight1 ?? '',
      item.plan?.weight2 ?? '',
      item.plan?.weight3 ?? '',
      item.plan?.weight4 ?? '',
      item.plan?.lot1 ?? '',
      item.plan?.lot2 ?? '',
      item.plan?.lot3 ?? '',
      item.plan?.lot4 ?? '',
      item.plan?.totalLots ?? '',
      item.plan?.totalDeployed ?? '',
      item.plan?.cashLeft ?? '',
      item.plan?.avgEntry ?? '',
      item.plan?.theoreticalAvgEntry ?? '',
      item.plan?.stopLoss ?? '',
      item.plan?.tp1 ?? '',
      item.plan?.tp2 ?? '',
      item.plan?.tp2Fib ?? '',
      item.plan?.riskPct ?? '',
      item.plan?.avgRiskPct ?? '',
      item.plan?.upsidePct ?? '',
      item.plan?.avgUpsidePct ?? '',
      item.plan?.rewardRisk ?? '',
      item.plan?.avgRewardRisk ?? '',
    ]),
  ];
}

export function serializeMaxScreenerCsvRows(rows: readonly (readonly unknown[])[]) {
  return rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n');
}

export function buildMaxScreenerCsv(results: ScanResult[]) {
  return serializeMaxScreenerCsvRows(buildMaxScreenerRows(results));
}
